//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder.Embedded v13.3.2+696a711
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Linq.Expressions;
using Umbraco.Cms.Core.Models.PublishedContent;
using Umbraco.Cms.Core.PublishedCache;
using Umbraco.Cms.Infrastructure.ModelsBuilder;
using Umbraco.Cms.Core;
using Umbraco.Extensions;

namespace Umbraco.Cms.Web.Common.PublishedModels
{
	/// <summary>Home page</summary>
	[PublishedModel("homePage")]
	public partial class HomePage : PublishedContentModel, IBeUpdatedProperties, IFeaturedProperties, IFooterProperties, IHeaderProperties, ILatestActivitiesProperties, INavigationProperties, INewspaperQuotesProperties, IOurFeaturedLocationProperties, IOurLabsProperties, IOurPark, IPartnersProperties, IServicesProperty, IStatisticsProperties, ISuccessStoriesProperty
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.3.2+696a711")]
		public new const string ModelTypeAlias = "homePage";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.3.2+696a711")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.3.2+696a711")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public new static IPublishedContentType GetModelContentType(IPublishedSnapshotAccessor publishedSnapshotAccessor)
			=> PublishedModelUtility.GetModelContentType(publishedSnapshotAccessor, ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.3.2+696a711")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(IPublishedSnapshotAccessor publishedSnapshotAccessor, Expression<Func<HomePage, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(publishedSnapshotAccessor), selector);
#pragma warning restore 0109

		private IPublishedValueFallback _publishedValueFallback;

		// ctor
		public HomePage(IPublishedContent content, IPublishedValueFallback publishedValueFallback)
			: base(content, publishedValueFallback)
		{
			_publishedValueFallback = publishedValueFallback;
		}

		// properties

		///<summary>
		/// AboutSTP
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.3.2+696a711")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("aboutSTP")]
		public virtual string AboutStp => this.Value<string>(_publishedValueFallback, "aboutSTP");

		///<summary>
		/// AboutSTPDescription
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.3.2+696a711")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("aboutSTPDescription")]
		public virtual string AboutStpdescription => this.Value<string>(_publishedValueFallback, "aboutSTPDescription");

		///<summary>
		/// AboutSTPImage
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.3.2+696a711")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("aboutSTPImage")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops AboutStpimage => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "aboutSTPImage");

		///<summary>
		/// OurFeatured
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.3.2+696a711")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("ourFeatured")]
		public virtual string OurFeatured => this.Value<string>(_publishedValueFallback, "ourFeatured");

		///<summary>
		/// STPVision
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.3.2+696a711")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("sTPVision")]
		public virtual string STpvision => this.Value<string>(_publishedValueFallback, "sTPVision");

		///<summary>
		/// STPVisionDescription
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.3.2+696a711")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("sTPVisionDescription")]
		public virtual string STpvisionDescription => this.Value<string>(_publishedValueFallback, "sTPVisionDescription");

		///<summary>
		/// STPVisionImage
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.3.2+696a711")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("sTPVisionImage")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops STpvisionImage => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "sTPVisionImage");

		///<summary>
		/// BeUpdatedDescription
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.3.2+696a711")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("beUpdatedDescription")]
		public virtual string BeUpdatedDescription => global::Umbraco.Cms.Web.Common.PublishedModels.BeUpdatedProperties.GetBeUpdatedDescription(this, _publishedValueFallback);

		///<summary>
		/// BeUpdatedSubscribe
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.3.2+696a711")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("beUpdatedSubscribe")]
		public virtual string BeUpdatedSubscribe => global::Umbraco.Cms.Web.Common.PublishedModels.BeUpdatedProperties.GetBeUpdatedSubscribe(this, _publishedValueFallback);

		///<summary>
		/// BeUpdatedTitle
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.3.2+696a711")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("beUpdatedTitle")]
		public virtual string BeUpdatedTitle => global::Umbraco.Cms.Web.Common.PublishedModels.BeUpdatedProperties.GetBeUpdatedTitle(this, _publishedValueFallback);

		///<summary>
		/// Main Content
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.3.2+696a711")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("mainContent")]
		public virtual global::Umbraco.Cms.Core.Models.Blocks.BlockListModel MainContent => global::Umbraco.Cms.Web.Common.PublishedModels.FeaturedProperties.GetMainContent(this, _publishedValueFallback);

		///<summary>
		/// Footer Social Links: Enter the social links
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.3.2+696a711")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("footerSocialLinks")]
		public virtual global::System.Collections.Generic.IEnumerable<global::Umbraco.Cms.Core.Models.PublishedContent.SocialLink> FooterSocialLinks => global::Umbraco.Cms.Web.Common.PublishedModels.FooterProperties.GetFooterSocialLinks(this, _publishedValueFallback);

		///<summary>
		/// BannerImage: Enter the banner image
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.3.2+696a711")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("bannerImage")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops BannerImage => global::Umbraco.Cms.Web.Common.PublishedModels.HeaderProperties.GetBannerImage(this, _publishedValueFallback);

		///<summary>
		/// gateway
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.3.2+696a711")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("gateway")]
		public virtual string Gateway => global::Umbraco.Cms.Web.Common.PublishedModels.HeaderProperties.GetGateway(this, _publishedValueFallback);

		///<summary>
		/// Subtitle: Enter you sup title
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.3.2+696a711")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("subtitle")]
		public virtual string Subtitle => global::Umbraco.Cms.Web.Common.PublishedModels.HeaderProperties.GetSubtitle(this, _publishedValueFallback);

		///<summary>
		/// Title: Enter a title for this page
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.3.2+696a711")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("title")]
		public virtual string Title => global::Umbraco.Cms.Web.Common.PublishedModels.HeaderProperties.GetTitle(this, _publishedValueFallback);

		///<summary>
		/// Main Content LatestActivities
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.3.2+696a711")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("mainContentLatestActivities")]
		public virtual global::Umbraco.Cms.Core.Models.Blocks.BlockListModel MainContentLatestActivities => global::Umbraco.Cms.Web.Common.PublishedModels.LatestActivitiesProperties.GetMainContentLatestActivities(this, _publishedValueFallback);

		///<summary>
		/// LogoIcon: Enter the logo icon
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.3.2+696a711")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("logoIcon")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops LogoIcon => global::Umbraco.Cms.Web.Common.PublishedModels.NavigationProperties.GetLogoIcon(this, _publishedValueFallback);

		///<summary>
		/// LogoText: Enter the Logo text
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.3.2+696a711")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("logoText")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops LogoText => global::Umbraco.Cms.Web.Common.PublishedModels.NavigationProperties.GetLogoText(this, _publishedValueFallback);

		///<summary>
		/// Main Navigations
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.3.2+696a711")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("mainNavigations")]
		public virtual global::System.Collections.Generic.IEnumerable<global::Umbraco.Cms.Core.Models.Link> MainNavigations => global::Umbraco.Cms.Web.Common.PublishedModels.NavigationProperties.GetMainNavigations(this, _publishedValueFallback);

		///<summary>
		/// Main Content Newspaper
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.3.2+696a711")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("mainContentNewspaper")]
		public virtual global::Umbraco.Cms.Core.Models.Blocks.BlockListModel MainContentNewspaper => global::Umbraco.Cms.Web.Common.PublishedModels.NewspaperQuotesProperties.GetMainContentNewspaper(this, _publishedValueFallback);

		///<summary>
		/// FirstPointOurFeaturedLocation
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.3.2+696a711")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("firstPointOurFeaturedLocation")]
		public virtual string FirstPointOurFeaturedLocation => global::Umbraco.Cms.Web.Common.PublishedModels.OurFeaturedLocationProperties.GetFirstPointOurFeaturedLocation(this, _publishedValueFallback);

		///<summary>
		/// MapTitleOurFeaturedLocation
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.3.2+696a711")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("mapTitleOurFeaturedLocation")]
		public virtual string MapTitleOurFeaturedLocation => global::Umbraco.Cms.Web.Common.PublishedModels.OurFeaturedLocationProperties.GetMapTitleOurFeaturedLocation(this, _publishedValueFallback);

		///<summary>
		/// OurFeaturedLocationTitle
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.3.2+696a711")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("ourFeaturedLocationTitle")]
		public virtual string OurFeaturedLocationTitle => global::Umbraco.Cms.Web.Common.PublishedModels.OurFeaturedLocationProperties.GetOurFeaturedLocationTitle(this, _publishedValueFallback);

		///<summary>
		/// SecondPointOurFeaturedLocation
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.3.2+696a711")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("secondPointOurFeaturedLocation")]
		public virtual string SecondPointOurFeaturedLocation => global::Umbraco.Cms.Web.Common.PublishedModels.OurFeaturedLocationProperties.GetSecondPointOurFeaturedLocation(this, _publishedValueFallback);

		///<summary>
		/// ThirdPointOurFeaturedLocation
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.3.2+696a711")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("thirdPointOurFeaturedLocation")]
		public virtual string ThirdPointOurFeaturedLocation => global::Umbraco.Cms.Web.Common.PublishedModels.OurFeaturedLocationProperties.GetThirdPointOurFeaturedLocation(this, _publishedValueFallback);

		///<summary>
		/// CentrallabsButton
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.3.2+696a711")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("centrallabsButton")]
		public virtual string CentrallabsButton => global::Umbraco.Cms.Web.Common.PublishedModels.OurLabsProperties.GetCentrallabsButton(this, _publishedValueFallback);

		///<summary>
		/// CentralLabsFirstDescription
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.3.2+696a711")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("centralLabsFirstDescription")]
		public virtual string CentralLabsFirstDescription => global::Umbraco.Cms.Web.Common.PublishedModels.OurLabsProperties.GetCentralLabsFirstDescription(this, _publishedValueFallback);

		///<summary>
		/// CentralLabsFirstImage
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.3.2+696a711")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("centralLabsFirstImage")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops CentralLabsFirstImage => global::Umbraco.Cms.Web.Common.PublishedModels.OurLabsProperties.GetCentralLabsFirstImage(this, _publishedValueFallback);

		///<summary>
		/// CentralLabsFirstTitle
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.3.2+696a711")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("centralLabsFirstTitle")]
		public virtual string CentralLabsFirstTitle => global::Umbraco.Cms.Web.Common.PublishedModels.OurLabsProperties.GetCentralLabsFirstTitle(this, _publishedValueFallback);

		///<summary>
		/// CentralLabsSecondDescription
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.3.2+696a711")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("centralLabsSecondDescription")]
		public virtual string CentralLabsSecondDescription => global::Umbraco.Cms.Web.Common.PublishedModels.OurLabsProperties.GetCentralLabsSecondDescription(this, _publishedValueFallback);

		///<summary>
		/// CentralLabsSecondImage
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.3.2+696a711")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("centralLabsSecondImage")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops CentralLabsSecondImage => global::Umbraco.Cms.Web.Common.PublishedModels.OurLabsProperties.GetCentralLabsSecondImage(this, _publishedValueFallback);

		///<summary>
		/// CentralLabsSecondTitle
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.3.2+696a711")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("centralLabsSecondTitle")]
		public virtual string CentralLabsSecondTitle => global::Umbraco.Cms.Web.Common.PublishedModels.OurLabsProperties.GetCentralLabsSecondTitle(this, _publishedValueFallback);

		///<summary>
		/// CentralLabsThirdDescription
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.3.2+696a711")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("centralLabsThirdDescription")]
		public virtual string CentralLabsThirdDescription => global::Umbraco.Cms.Web.Common.PublishedModels.OurLabsProperties.GetCentralLabsThirdDescription(this, _publishedValueFallback);

		///<summary>
		/// CentralLabsThirdImage
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.3.2+696a711")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("centralLabsThirdImage")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops CentralLabsThirdImage => global::Umbraco.Cms.Web.Common.PublishedModels.OurLabsProperties.GetCentralLabsThirdImage(this, _publishedValueFallback);

		///<summary>
		/// CentralLabsThirdTitle
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.3.2+696a711")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("centralLabsThirdTitle")]
		public virtual string CentralLabsThirdTitle => global::Umbraco.Cms.Web.Common.PublishedModels.OurLabsProperties.GetCentralLabsThirdTitle(this, _publishedValueFallback);

		///<summary>
		/// OurLabsTitle
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.3.2+696a711")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("ourLabsTitle")]
		public virtual string OurLabsTitle => global::Umbraco.Cms.Web.Common.PublishedModels.OurLabsProperties.GetOurLabsTitle(this, _publishedValueFallback);

		///<summary>
		/// ResearchDepartmentsButton
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.3.2+696a711")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("researchDepartmentsButton")]
		public virtual string ResearchDepartmentsButton => global::Umbraco.Cms.Web.Common.PublishedModels.OurLabsProperties.GetResearchDepartmentsButton(this, _publishedValueFallback);

		///<summary>
		/// ResearchDepartmentsFirstDescription
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.3.2+696a711")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("researchDepartmentsFirstDescription")]
		public virtual string ResearchDepartmentsFirstDescription => global::Umbraco.Cms.Web.Common.PublishedModels.OurLabsProperties.GetResearchDepartmentsFirstDescription(this, _publishedValueFallback);

		///<summary>
		/// ResearchDepartmentsFirstImage
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.3.2+696a711")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("researchDepartmentsFirstImage")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops ResearchDepartmentsFirstImage => global::Umbraco.Cms.Web.Common.PublishedModels.OurLabsProperties.GetResearchDepartmentsFirstImage(this, _publishedValueFallback);

		///<summary>
		/// ResearchDepartmentsFirstTitle
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.3.2+696a711")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("researchDepartmentsFirstTitle")]
		public virtual string ResearchDepartmentsFirstTitle => global::Umbraco.Cms.Web.Common.PublishedModels.OurLabsProperties.GetResearchDepartmentsFirstTitle(this, _publishedValueFallback);

		///<summary>
		/// ResearchDepartmentsSecondDescription
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.3.2+696a711")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("researchDepartmentsSecondDescription")]
		public virtual string ResearchDepartmentsSecondDescription => global::Umbraco.Cms.Web.Common.PublishedModels.OurLabsProperties.GetResearchDepartmentsSecondDescription(this, _publishedValueFallback);

		///<summary>
		/// ResearchDepartmentsSecondImage
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.3.2+696a711")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("researchDepartmentsSecondImage")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops ResearchDepartmentsSecondImage => global::Umbraco.Cms.Web.Common.PublishedModels.OurLabsProperties.GetResearchDepartmentsSecondImage(this, _publishedValueFallback);

		///<summary>
		/// ResearchDepartmentsSecondTitle
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.3.2+696a711")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("researchDepartmentsSecondTitle")]
		public virtual string ResearchDepartmentsSecondTitle => global::Umbraco.Cms.Web.Common.PublishedModels.OurLabsProperties.GetResearchDepartmentsSecondTitle(this, _publishedValueFallback);

		///<summary>
		/// ResearchDepartmentsThirdDescription
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.3.2+696a711")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("researchDepartmentsThirdDescription")]
		public virtual string ResearchDepartmentsThirdDescription => global::Umbraco.Cms.Web.Common.PublishedModels.OurLabsProperties.GetResearchDepartmentsThirdDescription(this, _publishedValueFallback);

		///<summary>
		/// ResearchDepartmentsThirdImage
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.3.2+696a711")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("researchDepartmentsThirdImage")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops ResearchDepartmentsThirdImage => global::Umbraco.Cms.Web.Common.PublishedModels.OurLabsProperties.GetResearchDepartmentsThirdImage(this, _publishedValueFallback);

		///<summary>
		/// ResearchDepartmentsThirdTitle
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.3.2+696a711")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("researchDepartmentsThirdTitle")]
		public virtual string ResearchDepartmentsThirdTitle => global::Umbraco.Cms.Web.Common.PublishedModels.OurLabsProperties.GetResearchDepartmentsThirdTitle(this, _publishedValueFallback);

		///<summary>
		/// SharedSuccessTitle
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.3.2+696a711")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("sharedSuccessTitle")]
		public virtual string SharedSuccessTitle => global::Umbraco.Cms.Web.Common.PublishedModels.OurLabsProperties.GetSharedSuccessTitle(this, _publishedValueFallback);

		///<summary>
		/// SpecializedLabsButton
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.3.2+696a711")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("specializedLabsButton")]
		public virtual string SpecializedLabsButton => global::Umbraco.Cms.Web.Common.PublishedModels.OurLabsProperties.GetSpecializedLabsButton(this, _publishedValueFallback);

		///<summary>
		/// SpecializedLabsFirstDescription
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.3.2+696a711")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("specializedLabsFirstDescription")]
		public virtual string SpecializedLabsFirstDescription => global::Umbraco.Cms.Web.Common.PublishedModels.OurLabsProperties.GetSpecializedLabsFirstDescription(this, _publishedValueFallback);

		///<summary>
		/// SpecializedLabsFirstImage
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.3.2+696a711")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("specializedLabsFirstImage")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops SpecializedLabsFirstImage => global::Umbraco.Cms.Web.Common.PublishedModels.OurLabsProperties.GetSpecializedLabsFirstImage(this, _publishedValueFallback);

		///<summary>
		/// SpecializedLabsFirstTitle
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.3.2+696a711")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("specializedLabsFirstTitle")]
		public virtual string SpecializedLabsFirstTitle => global::Umbraco.Cms.Web.Common.PublishedModels.OurLabsProperties.GetSpecializedLabsFirstTitle(this, _publishedValueFallback);

		///<summary>
		/// SpecializedLabsSecondDescription
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.3.2+696a711")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("specializedLabsSecondDescription")]
		public virtual string SpecializedLabsSecondDescription => global::Umbraco.Cms.Web.Common.PublishedModels.OurLabsProperties.GetSpecializedLabsSecondDescription(this, _publishedValueFallback);

		///<summary>
		/// SpecializedLabsSecondImage
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.3.2+696a711")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("specializedLabsSecondImage")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops SpecializedLabsSecondImage => global::Umbraco.Cms.Web.Common.PublishedModels.OurLabsProperties.GetSpecializedLabsSecondImage(this, _publishedValueFallback);

		///<summary>
		/// SpecializedLabsSecondTitle
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.3.2+696a711")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("specializedLabsSecondTitle")]
		public virtual string SpecializedLabsSecondTitle => global::Umbraco.Cms.Web.Common.PublishedModels.OurLabsProperties.GetSpecializedLabsSecondTitle(this, _publishedValueFallback);

		///<summary>
		/// SpecializedLabsThirdDescription
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.3.2+696a711")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("specializedLabsThirdDescription")]
		public virtual string SpecializedLabsThirdDescription => global::Umbraco.Cms.Web.Common.PublishedModels.OurLabsProperties.GetSpecializedLabsThirdDescription(this, _publishedValueFallback);

		///<summary>
		/// SpecializedLabsThirdImage
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.3.2+696a711")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("specializedLabsThirdImage")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops SpecializedLabsThirdImage => global::Umbraco.Cms.Web.Common.PublishedModels.OurLabsProperties.GetSpecializedLabsThirdImage(this, _publishedValueFallback);

		///<summary>
		/// SpecializedLabsThirdTitle
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.3.2+696a711")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("specializedLabsThirdTitle")]
		public virtual string SpecializedLabsThirdTitle => global::Umbraco.Cms.Web.Common.PublishedModels.OurLabsProperties.GetSpecializedLabsThirdTitle(this, _publishedValueFallback);

		///<summary>
		/// Main Content Our Park
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.3.2+696a711")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("mainContentOurPark")]
		public virtual global::Umbraco.Cms.Core.Models.Blocks.BlockListModel MainContentOurPark => global::Umbraco.Cms.Web.Common.PublishedModels.OurPark.GetMainContentOurPark(this, _publishedValueFallback);

		///<summary>
		/// Main Content Partners
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.3.2+696a711")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("mainContentPartners")]
		public virtual global::Umbraco.Cms.Core.Models.Blocks.BlockListModel MainContentPartners => global::Umbraco.Cms.Web.Common.PublishedModels.PartnersProperties.GetMainContentPartners(this, _publishedValueFallback);

		///<summary>
		/// Main Content Services
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.3.2+696a711")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("mainContentServices")]
		public virtual global::Umbraco.Cms.Core.Models.Blocks.BlockListModel MainContentServices => global::Umbraco.Cms.Web.Common.PublishedModels.ServicesProperty.GetMainContentServices(this, _publishedValueFallback);

		///<summary>
		/// FirstTextValue
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.3.2+696a711")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("firstTextValue")]
		public virtual string FirstTextValue => global::Umbraco.Cms.Web.Common.PublishedModels.StatisticsProperties.GetFirstTextValue(this, _publishedValueFallback);

		///<summary>
		/// FirstValue
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.3.2+696a711")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("firstValue")]
		public virtual string FirstValue => global::Umbraco.Cms.Web.Common.PublishedModels.StatisticsProperties.GetFirstValue(this, _publishedValueFallback);

		///<summary>
		/// ForthTextValue
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.3.2+696a711")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("forthTextValue")]
		public virtual string ForthTextValue => global::Umbraco.Cms.Web.Common.PublishedModels.StatisticsProperties.GetForthTextValue(this, _publishedValueFallback);

		///<summary>
		/// ForthValue
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.3.2+696a711")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("forthValue")]
		public virtual string ForthValue => global::Umbraco.Cms.Web.Common.PublishedModels.StatisticsProperties.GetForthValue(this, _publishedValueFallback);

		///<summary>
		/// SecondTextValue
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.3.2+696a711")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("secondTextValue")]
		public virtual string SecondTextValue => global::Umbraco.Cms.Web.Common.PublishedModels.StatisticsProperties.GetSecondTextValue(this, _publishedValueFallback);

		///<summary>
		/// SecondValue
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.3.2+696a711")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("secondValue")]
		public virtual string SecondValue => global::Umbraco.Cms.Web.Common.PublishedModels.StatisticsProperties.GetSecondValue(this, _publishedValueFallback);

		///<summary>
		/// ThirdTextValue
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.3.2+696a711")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("thirdTextValue")]
		public virtual string ThirdTextValue => global::Umbraco.Cms.Web.Common.PublishedModels.StatisticsProperties.GetThirdTextValue(this, _publishedValueFallback);

		///<summary>
		/// ThirdValue
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.3.2+696a711")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("thirdValue")]
		public virtual string ThirdValue => global::Umbraco.Cms.Web.Common.PublishedModels.StatisticsProperties.GetThirdValue(this, _publishedValueFallback);

		///<summary>
		/// Main Content Success Stories
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.3.2+696a711")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("mainContentSuccessStories")]
		public virtual global::Umbraco.Cms.Core.Models.Blocks.BlockListModel MainContentSuccessStories => global::Umbraco.Cms.Web.Common.PublishedModels.SuccessStoriesProperty.GetMainContentSuccessStories(this, _publishedValueFallback);
	}
}
