//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder.Embedded v13.3.2+696a711
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Linq.Expressions;
using Umbraco.Cms.Core.Models.PublishedContent;
using Umbraco.Cms.Core.PublishedCache;
using Umbraco.Cms.Infrastructure.ModelsBuilder;
using Umbraco.Cms.Core;
using Umbraco.Extensions;

namespace Umbraco.Cms.Web.Common.PublishedModels
{
	/// <summary>News Page</summary>
	[PublishedModel("newsPage")]
	public partial class NewsPage : PublishedContentModel, IContentProperties, IHeaderProperties, ILatestNewsProperty, INewspaperQuotesProperties
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.3.2+696a711")]
		public new const string ModelTypeAlias = "newsPage";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.3.2+696a711")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.3.2+696a711")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public new static IPublishedContentType GetModelContentType(IPublishedSnapshotAccessor publishedSnapshotAccessor)
			=> PublishedModelUtility.GetModelContentType(publishedSnapshotAccessor, ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.3.2+696a711")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(IPublishedSnapshotAccessor publishedSnapshotAccessor, Expression<Func<NewsPage, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(publishedSnapshotAccessor), selector);
#pragma warning restore 0109

		private IPublishedValueFallback _publishedValueFallback;

		// ctor
		public NewsPage(IPublishedContent content, IPublishedValueFallback publishedValueFallback)
			: base(content, publishedValueFallback)
		{
			_publishedValueFallback = publishedValueFallback;
		}

		// properties

		///<summary>
		/// AboutUs
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.3.2+696a711")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("aboutUs")]
		public virtual string AboutUs => global::Umbraco.Cms.Web.Common.PublishedModels.ContentProperties.GetAboutUs(this, _publishedValueFallback);

		///<summary>
		/// Body Text: Enter the text for this page
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.3.2+696a711")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("bodyText")]
		public virtual global::Umbraco.Cms.Core.Strings.IHtmlEncodedString BodyText => global::Umbraco.Cms.Web.Common.PublishedModels.ContentProperties.GetBodyText(this, _publishedValueFallback);

		///<summary>
		/// ContactUs
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.3.2+696a711")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("contactUs")]
		public virtual string ContactUs => global::Umbraco.Cms.Web.Common.PublishedModels.ContentProperties.GetContactUs(this, _publishedValueFallback);

		///<summary>
		/// Image
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.3.2+696a711")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("image")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops Image => global::Umbraco.Cms.Web.Common.PublishedModels.ContentProperties.GetImage(this, _publishedValueFallback);

		///<summary>
		/// BannerImage: Enter the banner image
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.3.2+696a711")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("bannerImage")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops BannerImage => global::Umbraco.Cms.Web.Common.PublishedModels.HeaderProperties.GetBannerImage(this, _publishedValueFallback);

		///<summary>
		/// gateway
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.3.2+696a711")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("gateway")]
		public virtual string Gateway => global::Umbraco.Cms.Web.Common.PublishedModels.HeaderProperties.GetGateway(this, _publishedValueFallback);

		///<summary>
		/// SubscribedFormm
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.3.2+696a711")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("subscribedFormm")]
		public virtual global::Umbraco.Cms.Core.Strings.IHtmlEncodedString SubscribedFormm => global::Umbraco.Cms.Web.Common.PublishedModels.HeaderProperties.GetSubscribedFormm(this, _publishedValueFallback);

		///<summary>
		/// Subtitle: Enter you sup title
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.3.2+696a711")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("subtitle")]
		public virtual string Subtitle => global::Umbraco.Cms.Web.Common.PublishedModels.HeaderProperties.GetSubtitle(this, _publishedValueFallback);

		///<summary>
		/// Title: Enter a title for this page
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.3.2+696a711")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("title")]
		public virtual string Title => global::Umbraco.Cms.Web.Common.PublishedModels.HeaderProperties.GetTitle(this, _publishedValueFallback);

		///<summary>
		/// AI Button
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.3.2+696a711")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("aIButton")]
		public virtual string AIbutton => global::Umbraco.Cms.Web.Common.PublishedModels.LatestNewsProperty.GetAIbutton(this, _publishedValueFallback);

		///<summary>
		/// Community Engagement Button
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.3.2+696a711")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("communityEngagementButton")]
		public virtual string CommunityEngagementButton => global::Umbraco.Cms.Web.Common.PublishedModels.LatestNewsProperty.GetCommunityEngagementButton(this, _publishedValueFallback);

		///<summary>
		/// Curriculum Development Button
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.3.2+696a711")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("curriculumDevelopmentButton")]
		public virtual string CurriculumDevelopmentButton => global::Umbraco.Cms.Web.Common.PublishedModels.LatestNewsProperty.GetCurriculumDevelopmentButton(this, _publishedValueFallback);

		///<summary>
		/// Diversity and Inclusion Button
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.3.2+696a711")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("diversityAndInclusionButton")]
		public virtual string DiversityAndInclusionButton => global::Umbraco.Cms.Web.Common.PublishedModels.LatestNewsProperty.GetDiversityAndInclusionButton(this, _publishedValueFallback);

		///<summary>
		/// Latest News Button
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.3.2+696a711")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("latestNewsButton")]
		public virtual string LatestNewsButton => global::Umbraco.Cms.Web.Common.PublishedModels.LatestNewsProperty.GetLatestNewsButton(this, _publishedValueFallback);

		///<summary>
		/// MainContentAI
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.3.2+696a711")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("mainContentAI")]
		public virtual global::Umbraco.Cms.Core.Models.Blocks.BlockListModel MainContentAI => global::Umbraco.Cms.Web.Common.PublishedModels.LatestNewsProperty.GetMainContentAI(this, _publishedValueFallback);

		///<summary>
		/// MainContentCommunityEngagement
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.3.2+696a711")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("mainContentCommunityEngagement")]
		public virtual global::Umbraco.Cms.Core.Models.Blocks.BlockListModel MainContentCommunityEngagement => global::Umbraco.Cms.Web.Common.PublishedModels.LatestNewsProperty.GetMainContentCommunityEngagement(this, _publishedValueFallback);

		///<summary>
		/// MainContentCurriculumDevelopment
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.3.2+696a711")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("mainContentCurriculumDevelopment")]
		public virtual global::Umbraco.Cms.Core.Models.Blocks.BlockListModel MainContentCurriculumDevelopment => global::Umbraco.Cms.Web.Common.PublishedModels.LatestNewsProperty.GetMainContentCurriculumDevelopment(this, _publishedValueFallback);

		///<summary>
		/// MainContentDiversityAndInclusion
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.3.2+696a711")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("mainContentDiversityAndInclusion")]
		public virtual global::Umbraco.Cms.Core.Models.Blocks.BlockListModel MainContentDiversityAndInclusion => global::Umbraco.Cms.Web.Common.PublishedModels.LatestNewsProperty.GetMainContentDiversityAndInclusion(this, _publishedValueFallback);

		///<summary>
		/// Main Content LatestNews
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.3.2+696a711")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("mainContentLatestNews")]
		public virtual global::Umbraco.Cms.Core.Models.Blocks.BlockListModel MainContentLatestNews => global::Umbraco.Cms.Web.Common.PublishedModels.LatestNewsProperty.GetMainContentLatestNews(this, _publishedValueFallback);

		///<summary>
		/// MainContentMentalHealth
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.3.2+696a711")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("mainContentMentalHealth")]
		public virtual global::Umbraco.Cms.Core.Models.Blocks.BlockListModel MainContentMentalHealth => global::Umbraco.Cms.Web.Common.PublishedModels.LatestNewsProperty.GetMainContentMentalHealth(this, _publishedValueFallback);

		///<summary>
		/// MainContentResearchAndStudies
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.3.2+696a711")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("mainContentResearchAndStudies")]
		public virtual global::Umbraco.Cms.Core.Models.Blocks.BlockListModel MainContentResearchAndStudies => global::Umbraco.Cms.Web.Common.PublishedModels.LatestNewsProperty.GetMainContentResearchAndStudies(this, _publishedValueFallback);

		///<summary>
		/// Main Content Technology
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.3.2+696a711")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("mainContentTechnology")]
		public virtual global::Umbraco.Cms.Core.Models.Blocks.BlockListModel MainContentTechnology => global::Umbraco.Cms.Web.Common.PublishedModels.LatestNewsProperty.GetMainContentTechnology(this, _publishedValueFallback);

		///<summary>
		/// Mental Health Button
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.3.2+696a711")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("mentalHealthButton")]
		public virtual string MentalHealthButton => global::Umbraco.Cms.Web.Common.PublishedModels.LatestNewsProperty.GetMentalHealthButton(this, _publishedValueFallback);

		///<summary>
		/// ResearchAndStudieButton
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.3.2+696a711")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("researchAndStudieButton")]
		public virtual string ResearchAndStudieButton => global::Umbraco.Cms.Web.Common.PublishedModels.LatestNewsProperty.GetResearchAndStudieButton(this, _publishedValueFallback);

		///<summary>
		/// Technology Button
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.3.2+696a711")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("technologyButton")]
		public virtual string TechnologyButton => global::Umbraco.Cms.Web.Common.PublishedModels.LatestNewsProperty.GetTechnologyButton(this, _publishedValueFallback);

		///<summary>
		/// Main Content Newspaper
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.3.2+696a711")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("mainContentNewspaper")]
		public virtual global::Umbraco.Cms.Core.Models.Blocks.BlockListModel MainContentNewspaper => global::Umbraco.Cms.Web.Common.PublishedModels.NewspaperQuotesProperties.GetMainContentNewspaper(this, _publishedValueFallback);
	}
}
